### PR TITLE
When building spec file, handle path names that contain spaces.

### LINKED ISSUE #428: Signed RPM creation fails on CentOS 7
During the build of the rpm I get thousands of lines of warnings about files listed twice. This breaks the sign-rpm script since it is unexpected output.

snippet from sign-rpm
````ruby
# match the expected prompt exactly, since that's the only way we know if
# something went wrong.
unless prompt == 'Enter pass phrase: '
  STDERR.puts "unexpected output from `#{rpm_cmd}`: '#{prompt}'"
  Process.kill(:KILL, pid)
  exit 1
end
````

output from omnibus
````
                    [Packager::RPM] D | Creating directory `/var/cache/omnibus/pkg'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/BUILD'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/RPMS'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/SRPMS'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/SOURCES'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/SPECS'
                    [Packager::RPM] D | Using vendored resource `filesystem_list'
                    [Packager::RPM] D | Using vendored resource `spec.erb'
                    [Packager::RPM] I | Rendering `/home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/resources/rpm/spec.erb' to `/tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec'
                    [Packager::RPM] I | Signing enabled for .rpm file
                    [Packager::RPM] I | Detected .rpmmacros file at `/home/vagrant'
                    [Packager::RPM] D | Using vendored resource `signing.erb'
                    [Packager::RPM] I | Rendering `/home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/resources/rpm/signing.erb' to `/tmp/d20150210-3935-nh775w/sign-rpm'

                    [Packager::RPM] I | Creating .rpm file
                    [Packager::RPM] D | Removing file `/tmp/d20150210-3935-nh775w/sign-rpm'
                    [Packager::RPM] D | Remove directory `/tmp/d20150210-3935-nh775w'
       STDERR: The following shell command exited with status 1:

           $ HOME=/home/vagrant LC_ALL=C /tmp/d20150210-3935-nh775w/sign-rpm "fakeroot rpmbuild -bb --buildroot /tmp/dms20150210-3935-1pn8rec/BUILD --define '_topdir /tmp/dms20150210-3935-1pn8rec' --sign /tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec"

       Output:

           fakeroot rpmbuild -bb --buildroot /tmp/dms20150210-3935-1pn8rec/BUILD --define '_topdir /tmp/dms20150210-3935-1pn8rec' --sign /tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec

       Error:

           unexpected output from `fakeroot rpmbuild -bb --buildroot /tmp/dms20150210-3935-1pn8rec/BUILD --define '_topdir /tmp/dms20150210-3935-1pn8rec' --sign /tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec`: 'warning: File liste'

       /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/util.rb:101:in `rescue in shellout!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/util.rb:97:in `shellout!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:325:in `block in create_rpm_file'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:370:in `call'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:370:in `with_rpm_signing'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:323:in `create_rpm_file'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:76:in `block in <class:RPM>'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/base.rb:144:in `instance_eval'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/base.rb:144:in `run!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/project.rb:955:in `package_me'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/project.rb:932:in `build_me'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:69:in `build'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli/base.rb:33:in `dispatch'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:41:in `execute!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/bin/omnibus:11:in `<top (required)>'
         bin/omnibus:16:in `load'
         bin/omnibus:16:in `<main>'
       ---- End output of bin/omnibus build dms --log-level debug ----
       Ran bin/omnibus build dms --log-level debug returned 1
       [2015-02-10T15:41:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
````

When run without sign-rpm...
````
warning: File listed twice: /opt/dms/bin
warning: File listed twice: /opt/dms/bin/dms-ctl
warning: File listed twice: /opt/dms/bin/dms-ctl
warning: File listed twice: /opt/dms/embedded
warning: File listed twice: /opt/dms/embedded/bin
warning: File listed twice: /opt/dms/embedded/bin
...
...
...
warning: File listed twice: /opt/dms/init
warning: File listed twice: /opt/dms/service
warning: File listed twice: /opt/dms/sv
warning: File listed twice: /opt/dms/version-manifest.txt
warning: Could not canonicalize hostname: default-centos-70.vagrantup.com
Enter pass phrase:
````

### PR DESCRIPTION
**Pull request by yzl**
cc @chef/ociv @danielsdeleo 

Fixes #428

### CODE REVIEW

**Comment by schisamo** [comment]
:+1:

File: spec/unit/packagers/rpm_spec.rb [hunk 1]
```diff
@@ -217,6 +218,7 @@ module Omnibus
           expect(contents).to include("/.file1")
           expect(contents).to include("%dir /dir2")
           expect(contents).to include("/file2")
+          expect(contents).to include("%dir \"/dir3 space\"")
```
Comment (danielsdeleo) [inline spec/unit/packagers/rpm_spec.rb]: I'm probably just being daft, but the change above seems to say there shouldn't be spaces here?

Comment (yzl) [inline spec/unit/packagers/rpm_spec.rb]: I stared at this too when I was adding the test.  Because of the space, the path name `/dir3 space` needs to be quoted in the spec file.  The problem I fixed was that we were taking the path name as including the double quotes, e.g. `"/dir3 space"`. Since that isn't the path name of an actual file, we didn't detect it as such and thus didn't mark the entry corresponding to the path `/dir3 space` as a directory in the spec file.

Comment (danielsdeleo) [inline spec/unit/packagers/rpm_spec.rb]: Ok, I get it now.

**Comment by danielsdeleo** [comment]
:+1: Thanks!

**Comment by scotthain** [comment]
:+1:
